// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//   },
// });

const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

console.log("=== Prisma chargé ===");
console.log(Object.keys(prisma));

module.exports = prisma;
